# Generated by Django 5.1 on 2024-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=80)),
                ('jobTitle', models.CharField(max_length=40)),
                ('unit_placement', models.CharField(max_length=40)),
                ('opd', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('sipil', 'sipil'), ('Non-ASN', 'Non-ASN')], default='sipil', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbPegawai',
            },
        ),
    ]
