# Generated by Django 5.1 on 2024-08-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pegawai_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='jobTitle',
            field=models.CharField(max_length=150),
        ),
    ]
