# Generated by Django 5.1 on 2024-10-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_beritaimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beritaimage',
            old_name='galeri',
            new_name='berita',
        ),
        migrations.AddField(
            model_name='galeri',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='galeriimage',
            table=None,
        ),
    ]
