# Generated by Django 5.1 on 2024-10-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_galeri_beritaimage_berita_galeri_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='berita',
            table=None,
        ),
        migrations.AlterModelTable(
            name='beritaimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='galeri',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pegawai',
            table=None,
        ),
    ]
