# Generated by Django 5.1 on 2024-10-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_berita_table_alter_beritaimage_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaleriImage',
        ),
    ]
