# Generated by Django 5.1 on 2024-10-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_galeriimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('galeri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.galeri')),
            ],
        ),
    ]
