# Generated by Django 5.1 on 2024-10-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_galeriimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaleriImage',
        ),
    ]
