# Generated by Django 5.1 on 2024-10-03 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_galeriimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='image',
        ),
    ]
